filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /home/ravi/Projects/Bemused/api-server/api-server/logs/*.log
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: after
output.logstash:
  hosts: ["localhost:5045"]
